# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  platformUrl: 'https://platform.42crunch.com'

steps:
- task: NodeTool@0
  displayName: Use Node 12 or higher
  inputs:
    versionSpec: '=12.0.0'

- task: APIContractSecurityAudit@3
  displayName: Auditing OAS Files
  inputs:
    apiToken: '$(42C_API_TOKEN)'
    minScore: '70'
    platformUrl: '$(platformUrl)'
    logLevel: DEBUG
    defaultCollectionName: 'Discovered APIs'
  env:
    BUILD_REPOSITORY_URI: '$(BUILD_REPOSITORY_URI)'
    BUILD_SOURCEBRANCH: '$(BUILD_SOURCEBRANCH)'
